# Generated by Django 5.1.5 on 2025-01-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movies_model_rated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_model',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
